# Generated by Django 6.0 on 2026-01-02 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_name', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('condition', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('contact_method', models.CharField(blank=True, choices=[('E', 'Email'), ('W', 'Whatsapp'), ('P', 'Phone')], max_length=1)),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Dashboard.userprofile')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_books', to='Dashboard.userprofile')),
            ],
        ),
    ]
