# Generated by Django 6.0 on 2026-01-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contact_method',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
